### ISSUE TITLE
BCALM 2 wtf: repart(max_minimizer) < repart(min_minimizer)

### ISSUE THREAD

**Issue by NickSto** [GATB/gatb-core#10] opened 2016-12-15 15:49 UTC
I was trying BCALM 2 (commit d47cf58) on some MiSeq data, and it failed with this error:
`wtf? traveller kmer = AAAAAATTCGT, min_minimizer=167 max_minimizer=1048575, repart(min_minimizer)=1, repart(max_minimizer)=0`
I found the [place](https://github.com/GATB/gatb-core/blob/master/gatb-core/src/gatb/bcalm2/bcalm_algo.cpp#L321) in the source the error came from, but I can't tell why it happened. I'm using a single, interleaved FASTQ file with 2.6 million reads. They're variable-length reads; do they have to be fixed-length, maybe?
Here's the full command line I used:
`$ bcalm -kmer-size 21 -abundance-min 10 -in SC8C1.fq -out k21a10/SC8C1.bcalm`
(It also failed with a -kmer-size of 11.)
I can't tell from the error message whether I'm doing something basic wrong, or if there's a problem with the input data. I read all the documentation I can find, and I couldn't see any obvious mistake I made.

**Comment by rchikhi** [comment] 2016-12-15 18:55
Hi Nick!
Input looks like what BCALM can take, and command line looks good. Variable-length reads are fine.
1) can you please pastebin the full output?
2) did bcalm work for you on another dataset, or does that bug occur for every dataset you try?

**Comment by NickSto** [comment] 2016-12-15 19:08
Hi Ryan, thanks for the reply! Paul pointed me to this tool and it looks like it could really help me out of a bind.
I should've mentioned, I did try it on the `example/tiny_read.fa` dataset (using `example/run-tiny.sh`) and it finished fine, without this bug.
The full stdout is [here](https://gist.github.com/NickSto/c0452364c8f83469613d52386b08b683), and the stderr is [here](https://gist.github.com/NickSto/0e3a487bb924fbcb904522ec355cc808).

**Comment by rchikhi** [comment] 2016-12-16 00:25
I see nothing out of the ordinary in the log files, except maybe:
1) 48 threads is more threads than I generally test with. Please try with "-nb-cores 1" added as a command line parameter
2) if it doesn't work, would you mind sending me the file? I'm on brubeck.

**Comment by NickSto** [comment] 2016-12-16 05:42
Oh, weird, I don't know how it ended up using 48 threads. I set it to 1 and it didn't fail with that error anymore! However, it failed with a different one:
```
[...]
Done with all compactions   --  memory [current, maximum (maxRSS)]: [ 661, 2177] MB 
Nb bglue threads: 1
unitigs graph destructor called
EXCEPTION: Unable to open bank 'k21a10n1/SC8C1.bcalm.unitigs.fa.glue'
```
And the output directory is no longer filled with dozens of files like `SC8C1.bcalm.unitigs.fa.glue.44` and `SC8C1.bcalm.unitigs.fa.doubledKmers.29`, but instead with only `SC8C1.bcalm.unitigs.fa.glue`, `SC8C1.bcalm.unitigs.fa.glue.0`, and `SC8C1.bcalm.h5`.
The input file is in scratch5, at `scratch5/nick/family/graph/bcalm/SC8C1/SC8C1.fq.gz`. I'll also try with some different inputs, just to check.

**Comment by NickSto** [comment] 2016-12-16 10:32
Update: I've narrowed it down to the choice of input.
I tried going back to the raw data, before quality filtering, and it worked! Somehow, the difference in the FASTQ files before and after filtering did it.
I filtered using [sickle](https://github.com/najoshi/sickle) (v1.33), which trims bad ends off reads and filters them out if there's not enough good sequence left. Here's the specific sickle command I used:
`$ sickle pe -t sanger -q 20 -l 100 -f $fastq1in -r $fastq2in -o $fastq1out -p $fastq2out -s $fastqs`
You can find the raw data on brubeck at:
`scratch1/boris/pnas_2014/mt.data/SC8C1-bl_[12].fq`
and the filtered data at:
`scratch5/nick/family/all4/fastq/filt/SC8C1-bl_[12].fq`
**Update to the update**: And now I can't reproduce the case where it works. No matter how I manipulate the input, I keep getting `EXCEPTION: Unable to open bank 'filename.bcalm.unitigs.fa.glue'`.
But that bank file exists and contains the name of another file, `filename.bcalm.unitigs.fa.glue.0`, which contains valid FASTA sequences.

**Comment by rchikhi** [comment] 2016-12-16 18:12
Hi Nick,

I've tried it on brubeck and it worked. So far I'm unable to reproduce the issue but let me try with the sickle data (I cannot access scratch5, just scratch and scratch2, but I'll run sickle).

1) Now it doesn't work for you, even using the raw input?
2) On which working directory did you run bcalm?

**Comment by rchikhi** [comment] 2016-12-16 18:13
Thanks for the data. I can reproduce the issue now. I think it is due to the "-out" argument pointing to another folder, if you remove this argument or ask to output in the same folder, it doesn't crash. I'll work on a fix.

**Comment by NickSto** [comment] 2016-12-16 18:56
Argh! Yep, that was it. Thanks so much for helping to figure this out!

**Comment by rchikhi** [comment] 2016-12-16 19:00
you're welcome, and i'm a bit embarassed about that bug in such a basic functionality :) let me know if you stumble on other issues with bcalm. especially if the original "wtf traveller kmer" error resurfaces.

**Comment by rchikhi** [comment] 2016-12-17 14:39
the -out bug has been fixed by commit https://github.com/GATB/gatb-core/commit/11a2aa11fcd9db031c7fb8f7bf883e729fec7b8a

**Closed as completed** 2016-12-23 03:43 UTC
